export const BaseUrl="http://127.0.0.1:8000/api/"
export const REGESTER ="register"
export const LOGIN ="login"
export const REFRESH ="refresh"
export const GET_CITY ="get-city"
export const GET_QIBLA ="getQiblaDirection"
export const AZKAR="categories"
export const BY_CATEGORY ="by-category"