import Grid from '@mui/material/Grid'
export const BaseUrl="http://127.0.0.1:8000/api/"
export const REGESTER ="register"
export const LOGIN ="login"
export const REFRESH ="refresh"
export const GET_CITY ="get-city"
export const GET_QIBLA ="getQiblaDirection"
export const AZKAR="categories"
export const BY_CATEGORY ="by-category"
export const GET_SUSTEICS ="get_staticsit_zekr"
export const UPDATE ="profile/update"
export const MAKEREAD ="markZekrAsRead"
export const GET_PAYRER_TIME ="getPrayerTimes"
export const NEXT ="getNextPrayer"
export const LOGOUT ="logout"
export const HIJRI="hijri/"
export const CALENDER="calendar"
export const CONVERT="convert"